/*
 * Li Song Mechlab - A 'mech building tool for PGI's MechWarrior: Online.
 * Copyright (C) 2013-2023  Li Song
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.lisoft.lsml.mwo_data.equipment;

import java.util.Collection;
import java.util.List;
import org.lisoft.lsml.mwo_data.Faction;
import org.lisoft.lsml.mwo_data.mechs.ChassisClass;
import org.lisoft.lsml.mwo_data.mechs.HardPointType;
import org.lisoft.lsml.mwo_data.mechs.Location;
import org.lisoft.lsml.mwo_data.modifiers.Attribute;
import org.lisoft.lsml.mwo_data.modifiers.Modifier;

/**
 * This is a base class for all items that can generate heat.
 *
 * <p>TODO: This class should contain all necessary information for heat calculations including heat
 * period and impulse length etc.
 *
 * @author Li Song
 */
public abstract class HeatSource extends Item {
  private final Attribute heat;

  protected HeatSource(
      // Item Arguments
      String aName,
      String aDesc,
      String aMwoName,
      int aMwoId,
      int aSlots,
      double aTons,
      HardPointType aHardPointType,
      double aHP,
      Faction aFaction,
      List<Location> aAllowedLocations,
      List<ChassisClass> aAllowedChassisClasses,
      // HeatSource Arguments
      Attribute aHeat) {
    super(
        aName,
        aDesc,
        aMwoName,
        aMwoId,
        aSlots,
        aTons,
        aHardPointType,
        aHP,
        aFaction,
        aAllowedLocations,
        aAllowedChassisClasses);
    heat = aHeat;
  }

  /**
   * Returns the total amount of heat generated for one activation. An activation is defined by the
   * implementing class.
   *
   * @param aModifiers A {@link Collection} of {@link Modifier}s that could affect the heat
   *     generation.
   * @return The amount of heat generated by each "action" of this heat source. The action is
   *     defined by the subclass.
   */
  public double getHeat(Collection<Modifier> aModifiers) {
    return heat.value(aModifiers);
  }
}
