package lisong_mechlab.model.loadout.metrics;

import lisong_mechlab.model.item.Engine;
import lisong_mechlab.model.item.Item;
import lisong_mechlab.model.item.Weapon;
import lisong_mechlab.model.loadout.Loadout;

/**
 * This {@link Metric} calculates how much heat is generated per second for a {@link Loadout} with "all guns blazing".
 * <p>
 * It accounts for the heat generated by the engine at 100% throttle but not for jump jets.
 * 
 * @author Emily Björk
 */
public class HeatGeneration implements Metric{
   private final Loadout loadout;

   public HeatGeneration(final Loadout aLoadout){
      loadout = aLoadout;
   }

   @Override
   public double calculate(){
      double heat = 0;
      for(Item item : loadout.getAllItems()){
         if( item instanceof Weapon ){
            heat += ((Weapon)item).getStat("h/s", loadout.getUpgrades());
         }
         else if( item instanceof Engine ){
            heat += ((Engine)item).getHeat();
         }
      }
      return heat;
   }
}
