/*
 * @formatter:off
 * Li Song Mechlab - A 'mech building tool for PGI's MechWarrior: Online.
 * Copyright (C) 2013  Emily Björk
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */  
//@formatter:on
package lisong_mechlab.model.loadout.metrics;

import lisong_mechlab.model.item.Engine;
import lisong_mechlab.model.item.Item;
import lisong_mechlab.model.item.Weapon;
import lisong_mechlab.model.loadout.Loadout;

/**
 * This {@link Metric} calculates how much heat is generated per second for a {@link Loadout} with "all guns blazing".
 * <p>
 * It accounts for the heat generated by the engine at 100% throttle but not for jump jets.
 * 
 * @author Emily Björk
 */
public class HeatGeneration implements Metric{
   private final Loadout loadout;

   public HeatGeneration(final Loadout aLoadout){
      loadout = aLoadout;
   }

   @Override
   public double calculate(){
      double heat = 0;
      for(Item item : loadout.getAllItems()){
         if( item instanceof Weapon ){
            heat += ((Weapon)item).getStat("h/s", loadout.getUpgrades(), loadout.getEfficiencies());
         }
         else if( item instanceof Engine ){
            heat += ((Engine)item).getHeat();
         }
      }
      return heat;
   }
}
